language: swift
osx_image: xcode10.3

jobs:
  include:
  - stage: build
    name: "Building iOS"
    script: bundle exec fastlane build_framework platform:'iOS'

  - stage: build
    name: "Building tvOS"
    script: bundle exec fastlane build_framework platform:'tvOS'

  - stage: build
    name: "Building example app"
    script: bundle exec fastlane build_example_app ios_version:'12.4'

  - stage: test
    name: "Running tests"
    script: bundle exec fastlane ios test device:'iPhone 8'

  - stage: test
    name: "Running performance tests"
    script: bundle exec fastlane ios test_performance device:'iPhone 8'
